services:
  - type: web
    name: linkedin-analyzer-backend
    env: python
    branch: main
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install --with-deps
    startCommand: cd backend gunicorn app:app
    runtime: python
