services:
  - type: web
    name: linkedin-analyzer-backend
    env: python
    branch: main
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python -m playwright install --with-deps
    startCommand: cd backend && gunicorn app:app
